modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Exidex/SwingThroughGrass/issues"
license="MIT"

[[mods]]
modId="swingthroughgrass"
version="${file.jarVersion}"
displayName="SwingThroughGrass"
displayURL="https://minecraft.curseforge.com/projects/swingthroughgrass"
logoFile="logo.png"
credits="Direwolf20, Darkosto"
authors="Exidex"
description='''Don't let the grass be between you and your prey!'''

[[dependencies.swingthroughgrass]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swingthroughgrass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
